# Docker-compose configuration for production

version: '2.1'

services:
    django:
        build:
            context: .
            dockerfile: Dockerfile-django.production
        container_name: tonis_piip_org_django
        restart: unless-stopped
        volumes:
            - "/var/lib/docker-nginx/files/tonis_piip_org/assets:/files/assets"
            - "/var/log/tonis_piip_org:/var/log/tonis_piip_org"
        # For some reason the command also has to be specified here, otherwise the entrypoint+command combination won't
        #  work.
        entrypoint: /usr/bin/wait-for-it.sh postgres:5432 -t 60 --
        command: gunicorn tonis_piip_org.wsgi:application --workers 2 --bind :80
        networks:
            - default
            - tonis_piip_org_nginx
            - tonis_piip_org_postgres
        depends_on:
            - redis
        external_links:
            - postgres-10:postgres

    celery:
        build:
            context: .
            dockerfile: Dockerfile-django.production
        restart: unless-stopped
        volumes:
            - "/var/log/tonis_piip_org:/var/log/tonis_piip_org"
        networks:
            - default
            - tonis_piip_org_postgres
        depends_on:
            - redis
        external_links:
            - postgres-10:postgres
        entrypoint: /usr/bin/wait-for-it.sh postgres:5432 -t 60 --
        command: celery worker --app tonis_piip_org --autoscale 6,2 --loglevel INFO

    celery_beat:
        build:
            context: .
            dockerfile: Dockerfile-django.production
        container_name: tonis_piip_org_celery_beat
        restart: unless-stopped
        volumes:
            - "/var/lib/docker-tonis_piip_org/celery:/celery"
            - "/var/log/tonis_piip_org:/var/log/tonis_piip_org"
        networks:
            - default
        depends_on:
            - redis
        # Disable pidfile by specifying an empty one. We used fixed container_name which provides single-running-process
        #  guarantee and the lack of pidfile ensures that Celery Beat starts even if the Docker container was killed and
        #  then restarted (in which case the pidfile would still be present).
        command: celery beat --app tonis_piip_org --loglevel INFO --logfile /var/log/tonis_piip_org/celery-beat.log --pidfile= --schedule /celery/celerybeat-schedule

    redis:
        image: redis:4.0.10-alpine
        restart: unless-stopped
        sysctls:
            # To allow maintaining TCP backlog setting that defaults to 511
            net.core.somaxconn: 512
        volumes:
            - "/var/lib/docker-tonis_piip_org/redis:/data"
        networks:
            - default

# NB: These networks must be created by fabfile and contain the global nginx/postgres containers.
# Keep it in sync with fabfile!
networks:
    default:
        external:
            name: tonis_piip_org_default
    tonis_piip_org_nginx:
        external: true
    tonis_piip_org_postgres:
        external: true
